### PR TITLE
Allow eventfd to be zero

### PR DESCRIPTION
**Pull request by bsbernd**
Result of eventfd() might be zero - this is a valid file descriptor.

Also always return -errno (and 0) from ublksrv_setup_eventfd() and use it for the error message.

### CODE REVIEW

**Comment by bsbernd** [comment]
@ming1 Just wanted to check how to use polling on the ring fd and noticed that q->efd was assumed to be never 0.

**Comment by ming1** [comment]
> Result of eventfd() might be zero - this is a valid file descriptor.

file descriptor 0 is reserved for standard input, so it shouldn't be
returned from eventfd().

Do you see any problem with current way of treating zero
as failure?

Thanks,

**Comment by bsbernd** [comment]
I was just looking something up in the code, without using it. It is ensured that stdin is still open when eventfd is set up, in all cases? Just very unusual to treat fd=0 as special...

**Comment by ming1** [comment]
> I was just looking something up in the code, without using it. It is ensured that stdin is still open when eventfd is set up, in all cases? Just very unusual to treat fd=0 as special...

Fair enough, merged.

thanks,

**Pull request merged**
